DRAFT: Text editor
fiaisis/admin-portal pull request #14
Opened 2024-06-04 10:15 UTC by HumzahJavid

Closes # 

## Description

2024-06-04 13:26 UTC, Pasarus requested changes
Just some comments to make, let me know if nothing is clear.

The button needs to either be at the top of the page or somewhere more sane than beneath the starting page.

Would it be possible to "prettify" the default json?

With regards to the overall layout, could the instrument list be made thinner? I think it's now obvious that it requires less space?

2024-06-05 14:00 UTC, HumzahJavid commented
Thanks for the discussion @keiranjprice101 .
I will add a title above the code editor as you suggested, and move the button to a similar location

2024-06-05 16:01 UTC, HumzahJavid commented
All unused (commented out) code/comments were removed in 3dcc530

2024-06-06 12:39 UTC, HumzahJavid commented
I have updated the top level PR comment with all the changes in this PR.

2024-06-06 13:40 UTC, keiranjprice101 commented on src/components/TextEditor.tsx
> +      }, 5000);
Can you add a comment at the end of this line like `// 5 seconds`

2024-06-06 13:41 UTC, keiranjprice101 commented on src/app/page.tsx
> +          <EditorHeader title={instrument}></EditorHeader>
Can you put this into a single tag `<EditorHeader title={instrument} />`

2024-06-06 13:42 UTC, keiranjprice101 requested changes
Few minor things

2024-06-06 13:56 UTC, keiranjprice101 approved these changes

2024-06-06 13:56 UTC, merged